### ISSUE TITLE
Pseudo-selectors deprecation

### ISSUE THREAD

**Issue by michelegera** [pveyes/atom-snazzy-clear-syntax#5]
After updating Atom to v1.13.0, I got this deprecation warning:

“Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:”

[[Long list of selectors](https://gist.github.com/michelegera/6aa996d3ee82e03c6d3d2f5b3d566fa2)]

Automatic translation of selectors will be removed in a few release cycles to minimize startup time.

**Comment by pveyes** [comment]
Released in `v0.3.0` 🎉
