### ISSUE TITLE
Snazzy brackets too dark

### ISSUE THREAD

**Issue by drcmda** [pveyes/atom-snazzy-clear-syntax#8]
Just going to say, it looks awesome! But brackets are so dark it makes it a little impractical for work. Could you lift them at least a little bit?

**Comment by pveyes** [comment]
Thanks. I may take it a little too extreme because I don't really like seeing punctuation 😂 .

Could you submit a PR with a screenshot so I can get a better look of what you want?

**Comment by pveyes** [comment]
I've made some changes to the bracket color in 2b0b86903af4831a1ef52d0796b01c09d2e51306 so it will have the same color as comment.

**Comment by drcmda** [comment]
@pveyes thanks, very happy with it!
